# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pdf-analyser-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_c5f1da8df37b4143a438e5f0be754b7a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_01c4c1624fa5425ea30606fdab9fab2f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_c5f1da8df37b4143a438e5f0be754b7a }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pdf-analyser-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7f122923cc8e40fbb9a900c4faebf308 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_c5f1da8df37b4143a438e5f0be754b7a }}/appsvc/staticsite:${{ github.sha }}'